homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Assistant
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 39
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature

  - platform: worldclock
    time_zone: America/New_York

  - platform: cpuspeed
  
  - platform: bitcoin
    display_options:
      - exchangerate
      - trade_volume_btc
      
  - platform: coinmarketcap    
    currency_id: 1027
    
  - platform: coinmarketcap
    currency_id: 52
    
  - platform: coinmarketcap
    currency_id: 1831
    
  - platform: coinmarketcap
    currency_id: 1765
    
  - platform: cointmarketcap
    currency_id: 512
    
  - platform: cointmarketcap
    currency_id: 2
    
  - platform: cointmarketcap
    currency_id: 825
  
  - platform: coinmarketcap
    currency_id: 2010
    
  - platform: coinmarketcap 
    currency_id: 328
    
  - platform: coinmarketcap
    currency_id: 1958
      
  - platform: miflora
    mac: 'c4:7c:8d:62:da:c2'
    name: Phytotron
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  

# Text to speech
tts:
  - platform: google
    language: 'fr'

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
